import os


TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']
TWILIO_SENDER_NUMBER = os.environ['TWILIO_SENDER_NUMBER']
TWILIO_RECIPIENT_NUMBER = os.environ['TWILIO_RECIPIENT_NUMBER']
TWILIO_MEDIA_URL = os.environ['TWILIO_MEDIA_URL']
